# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 03:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer1', '0002_help_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='sold_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
