# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer1', '0003_auto_20181029_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='name',
        ),
    ]
